language: python
python:
  - '3.6'
install:
  - pip3 install coala-bears
  - npm install mocha -g
script:
  - coala
  - mocha src/test/
before_deploy:
  - gulp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build/
  repo: marceloabk/addy-web
  target_branch: master
  on:
    branch: master